resolver: nightly-2022-03-03

# paths to local packages
packages:
  - cabal-pkg-config-version-hook
  # - hercules-ci-cnix-store
  - hercules-ci-cnix-expr
  - hercules-ci-api
  - hercules-ci-api-core
  - hercules-ci-api-agent
  - hercules-ci-agent
  - hercules-ci-cli
  - tests/agent-test
extra-deps:
  # Putting hercules-ci-cnix-store in packages confuses hie-bios wrt cachix deps
  - ./hercules-ci-cnix-store
  - git: https://github.com/hercules-ci/optparse-applicative.git
    commit:
      # PRs: roughly https://github.com/pcapriotti/optparse-applicative/pulls/roberth
      # branch: fork
      9e2968c09a7c5b29d04578dc68d81ce5aec0591e
  # REMINDER: sync with scripts/generate-nix
  # - git: https://github.com/hercules-ci/cachix.git
  #   commit: f24e3048fbc81a98e9ad7a7bcfe877c2bc1b4b9b
  #   subdirs:
  #     - cachix
  #     - cachix-api
  - cachix-0.6.1
  - cachix-api-0.6.0
  - inline-c-0.9.1.4
  - inline-c-cpp-0.4.0.2
  - ListLike-4.7.4@sha256:613b2967df738010e8f6f6b7c47d615f6fe42081f68eba7f946d5de7552aa8a4,3778
  - process-extras-0.7.4@sha256:4e79289131415796c181889c4a226ebab7fc3b0d27b164f65e1aad123ae9b9e3,1759
  - git: https://github.com/protolude/protolude
    commit: 1b453b60645faf44820d8cb841755e5f20ac1d11
  - netrc-0.2.0.0@sha256:0e1e6e3f3fbd83c26c0e5edec27098bed99219afaaeeebf9ff19aedff1e4b332,2145
  - nix-derivation-1.0.2@sha256:dc1f13f89d37d4dcc7a46dbac7f6b4e8cd2877f4af99e35b9cb8255d08179bd4,3123
  - nix-narinfo-0.1.0.1@sha256:53d9ee364e14815b058c14e3056157f0245ba97972806ae3916a50f035955ea9,2111
  - servant-websockets-2.0.0@sha256:6e9e3600bced90fd52ed3d1bf632205cb21479075b20d6637153cc4567000234,2253
  - tomland-1.3.3.1
  - servant-swagger-ui-core-0.3.5
  - validation-selective-0.1.0.1

install-ghc: false  # we're using nixpkgs' ghc
system-ghc: true    # nixpkgs ghc is perceived as 'system ghc'

ghc-options:
  # trick stack repl to remove optparse-applicative, so we only get the fork in HLS
  hercules-ci-agent-test: -hide-package optparse-applicative

nix:
  packages: []      # use shell instead
  shell-file: ./nix/stack-shell.nix
  pure: false
